import 'dart:io';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../../../data/models/booking_model.dart';
import '../../../data/models/user_model.dart';

class PDFReportService {
  static Future<void> generateCustomerReport({
    required UserModel customer,
    required List<BookingModel> bookings,
  }) async {
    final pdf = pw.Document();

    final font = await PdfGoogleFonts.outfitRegular();
    final boldFont = await PdfGoogleFonts.outfitBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('GlamBook Salon History Report', style: pw.TextStyle(font: boldFont, fontSize: 24)),
                    pw.Text(DateFormat('dd/MM/yyyy').format(DateTime.now()), style: pw.TextStyle(font: font)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Customer Details:', style: pw.TextStyle(font: boldFont, fontSize: 18)),
              pw.SizedBox(height: 10),
              pw.Text('Name: ${customer.fullName}', style: pw.TextStyle(font: font)),
              pw.Text('Email: ${customer.email}', style: pw.TextStyle(font: font)),
              pw.Text('Phone: ${customer.phone}', style: pw.TextStyle(font: font)),
              if (customer.skinType != null) pw.Text('Skin Type: ${customer.skinType}', style: pw.TextStyle(font: font)),
              if (customer.skinSensitivity != null) pw.Text('Sensitivity: ${customer.skinSensitivity}', style: pw.TextStyle(font: font)),
              pw.SizedBox(height: 30),
              pw.Text('Booking History:', style: pw.TextStyle(font: boldFont, fontSize: 18)),
              pw.SizedBox(height: 10),
              pw.Table(
                border: pw.TableBorder.all(),
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                    children: [
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('Date', style: pw.TextStyle(font: boldFont))),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('Service', style: pw.TextStyle(font: boldFont))),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('Status', style: pw.TextStyle(font: boldFont))),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('Price', style: pw.TextStyle(font: boldFont))),
                    ],
                  ),
                  ...bookings.map((b) => pw.TableRow(
                    children: [
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text(DateFormat('dd/MM/yy').format(b.appointmentDate), style: pw.TextStyle(font: font))),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text(b.serviceSnapshot['name'], style: pw.TextStyle(font: font))),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text(b.status.name, style: pw.TextStyle(font: font))),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('\$${b.serviceSnapshot['price']}', style: pw.TextStyle(font: font))),
                    ],
                  )),
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Divider(),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Total Visits: ${bookings.length}', style: pw.TextStyle(font: boldFont)),
                      pw.Text('Total Spending: PKR ${bookings.fold<double>(0, (sum, b) => sum + (b.serviceSnapshot['price'] ?? 0))}', style: pw.TextStyle(font: boldFont, color: PdfColors.pink)),
                    ],
                  ),
                  pw.Text('Generated by GlamBook Admin', style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey600)),
                ],
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
