// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzPtk1KB7G1ADfW-tTCCLfVPyTN-6k3Mg',
    appId: '1:24943436991:web:26c615dacb1035cd5b520a',
    messagingSenderId: '24943436991',
    projectId: 'glam-book-7b109',
    authDomain: 'glam-book-7b109.firebaseapp.com',
    storageBucket: 'glam-book-7b109.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTFm6byGmZUpFna3Y4G9524x-Vl7C6KUY',
    appId: '1:24943436991:android:32c4bfeeef60400c5b520a',
    messagingSenderId: '24943436991',
    projectId: 'glam-book-7b109',
    storageBucket: 'glam-book-7b109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqzVZnzupQSxZmF76C8HV3AvzLzQhMRD8',
    appId: '1:24943436991:ios:e68cadc5055062825b520a',
    messagingSenderId: '24943436991',
    projectId: 'glam-book-7b109',
    storageBucket: 'glam-book-7b109.firebasestorage.app',
    iosBundleId: 'com.example.glamBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqzVZnzupQSxZmF76C8HV3AvzLzQhMRD8',
    appId: '1:24943436991:ios:e68cadc5055062825b520a',
    messagingSenderId: '24943436991',
    projectId: 'glam-book-7b109',
    storageBucket: 'glam-book-7b109.firebasestorage.app',
    iosBundleId: 'com.example.glamBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzPtk1KB7G1ADfW-tTCCLfVPyTN-6k3Mg',
    appId: '1:24943436991:web:c4eb46fc2f9f45965b520a',
    messagingSenderId: '24943436991',
    projectId: 'glam-book-7b109',
    authDomain: 'glam-book-7b109.firebaseapp.com',
    storageBucket: 'glam-book-7b109.firebasestorage.app',
  );
}
